# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daley Codes
author: Daley Mikalson
email: hi@daleym.ca
description: > # this means to ignore newlines until "baseurl:"
  I am a civil engineer and though I dabbled with coding in university did not ever use it effectively until grad school. This site is for posting about coding projects and other learning activities.
baseurl: "" # the subpath of your site, e.g. /blog
paginate: 3
twitter_username: lingwhatics
github_username:  lingwhatics

# Build settings
markdown: kramdown
gems:
   - jekyll-paginate