# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daley's blog
author: Daley Mikalson
email: hi@daleym.ca
description: > # this means to ignore newlines until "baseurl:"
  Daley's blog where he writes stuff
url: http://lingwhatics.ca
baseurl: # the subpath of your site, e.g. /blog
paginate: 7
twitter_username: lingwhatics
github_username:  lingwhatics

# Build settings
markdown: kramdown
gems:
   - jekyll-paginate
